//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string FileType { get; set; }
        public string FileRoot { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string AuthorId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
